steps:
  build:
    image: python:3.11
    commands:
      - pip install -r requirements.txt
      - echo "✅ Linting & Tests à venir ici"
    when:
      event: [push]
      branch: [main]

  dockerize:
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      repo: geodata_api
      tags: latest
    when:
      event: [push]
      branch: [main]

  deploy:
    image: docker
    commands:
      - docker compose down
      - docker compose up -d --build
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      event: [push]
      branch: [main]
