when:
  event: [push, manual]
  branch: [main, dev]

steps:
  build:
    image: python:3.11
    commands:
      - pip install -r requirements.txt
      - echo "✅ Linting & Tests à venir ici"

  dockerize:
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      repo: geodata_api
      tags: latest

  deploy-prod:
    image: docker/compose:1.29.2
    commands:
      - docker-compose -f docker-compose.prod.yml up -d --build
    when:
      branch: [main]
      event: [push, manual]

  deploy-staging:
    image: docker/compose:1.29.2
    commands:
      - docker-compose -f docker-compose.staging.yml up -d --build
    when:
      branch: [dev]
      event: [push, manual]
