steps:
  debug:
    image: alpine
    commands:
      - echo "✅ Pipeline déclenché sur ${CI_COMMIT_BRANCH}"
      - "echo Event déclencheur : ${CI_PIPELINE_EVENT}"
    when:
      event: [push, manual, pull_request]

  build:
    image: python:3.11
    commands:
      - echo "🧪 Nouveau build à $(date) pour test"
      - pip install -r requirements.txt
      - echo "✅ Linting & Tests à venir ici"
    when:
      branch: [main, dev]
      event: [push, manual]

  deploy-staging:
    image: docker/compose:1.29.2
    privileged: true
    depends_on: [build]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DB_HOST:
        from_secret: DB_HOST
      DB_PORT:
        from_secret: DB_PORT
      DB_USER:
        from_secret: DB_USER
      DB_PASSWORD:
        from_secret: DB_PASSWORD
      DB_NAME:
        from_secret: DB_NAME
    commands:
      - docker-compose -f docker-compose.staging.yml -p geodata_api_staging down --remove-orphans || true
      - docker-compose -f docker-compose.staging.yml -p geodata_api_staging up -d --build --remove-orphans
      - docker-compose -f docker-compose.staging.yml -p geodata_api_staging run --rm pytest
      - sleep 5
    when:
      branch: [dev]
      event: [push, manual]

  deploy-prod:
    image: docker/compose:1.29.2
    depends_on: [build]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DB_HOST:
        from_secret: DB_HOST
      DB_PORT:
        from_secret: DB_PORT
      DB_USER:
        from_secret: DB_USER
      DB_PASSWORD:
        from_secret: DB_PASSWORD
      DB_NAME:
        from_secret: DB_NAME
    commands:
      - docker-compose -f docker-compose.prod.yml -p geodata_api_prod down --remove-orphans || true
      - docker-compose -f docker-compose.prod.yml -p geodata_api_prod up -d --build --remove-orphans
    when:
      branch: [main]
      event: [push, manual]
