steps:
  build:
    image: python:3.11
    commands:
      - pip install -r requirements.txt
      - echo "✅ Linting & Tests à venir ici"
    when:
      event: [push]
      branch: [main]

  dockerize:
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      repo: geodata_api
      tags: latest
    when:
      event: [push]
      branch: [main]

  deploy:
    image: docker/compose:1.29.2
    commands:
      - docker-compose down
      - docker-compose up -d --build
    when:
      event: [push]
      branch: [main]
