version: "3.9"

services:
  api:
    build: .
    container_name: geodata_api_staging
    ports:
      - "8010:80"
    environment:
      DB_HOST: postgres_geodata
      DB_PORT: 5432
      DB_USER: roger
      DB_PASSWORD: motdepassefort
      DB_NAME: geodata
    networks:
      - geodata_db_backend_net
    restart: unless-stopped

  pytest:
    image: python:3.11
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "pip install -r requirements.txt && pytest test.py"
    environment:
      DB_HOST: postgres_geodata
      DB_PORT: 5432
      DB_USER: roger
      DB_PASSWORD: motdepassefort
      DB_NAME: geodata
    depends_on:
      - api
    networks:
      - geodata_db_backend_net

networks:
  geodata_db_backend_net:
    external: true
