version: "3.9"

services:
  api_staging:
    build: .
    container_name: geodata_api_staging
    ports:
      - "8010:80"
    env_file:
      - env/.env.staging

  api_prod:
    build: .
    container_name: geodata_api_prod
    ports:
      - "8000:80"
    env_file:
      - env/.env.prod
