version: "3.9"

services:
  api:
    build: .
    container_name: geodata_api_prod
    ports:
      - "8000:80"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    restart: unless-stopped
    networks:
      - backend_net
      - woodpecker_default

networks:
  backend_net:
    external: true
    name: geodata_backend_net  # ✅ le nom réel du réseau Docker
  woodpecker_default:
    external: true
