version: "3.9"

services:
  api:
    build: .
    container_name: geodata_api_staging
    ports:
      - "8010:80"
    environment:
      DB_HOST: postgres_geodata  # Nom du conteneur PostgreSQL déjà lancé en local
      DB_PORT: 5432
      DB_USER: roger
      DB_PASSWORD: motdepassefort
      DB_NAME: geodata

    networks:
      - backend_net

networks:
  backend_net:
    external: true
    name: geodata_db_backend_net
