version: "3.9"

services:
  api:
    build: .
    container_name: geodata_api_staging
    ports:
      - "8010:80"
    environment:
      DB_HOST: postgres_geodata  # Nom du conteneur PostgreSQL déjà lancé en local
      DB_PORT: 5432
      DB_USER: roger
      DB_PASSWORD: motdepassefort
      DB_NAME: geodata

    networks:
      - geodata_db_backend_net  # 👈 réseau existant
    restart: unless-stopped

networks:
  backend_net:
    external: true
    name: geodata_db_backend_net

    - sleep 5
    - curl -s -o /dev/null -w "%{http_code}" http://localhost:8010/data | grep 200 || (echo "❌ Endpoint KO" && exit 1)
