version: "3.9"

services:
  api:
    build: .
    container_name: geodata_api_staging
    ports:
      - "8010:80"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    networks:
      - geodata_db_backend_net
    restart: unless-stopped

  pytest:
    image: geodata_api_staging_api
    working_dir: /app
    command: sh -c "pip install -r requirements.txt && pytest test.py"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - api
    networks:
      - geodata_db_backend_net

networks:
  geodata_db_backend_net:
    external: true
